---
title: "Bivariate Plot"
author: "Alexandria Coombe"
format: 
  html: 
    embed-resources: true
    self-contained-math: true
---

```{r}
cannabisDataset <- read.csv("cannabisDataset.csv",
                        header = TRUE)
head(cannabisDataset)
```



```{r}
library(dplyr)
library(stringr)

cannabisDataset <- cannabisDataset %>%
  mutate_all(str_squish)

cannabisDataset <- cannabisDataset %>%
 mutate_all(~ifelse(tolower(.) %in% c("yes", "Yes"), 1, ifelse(tolower(.) %in% c("no", "No"), 0, .)))
```


```{r}
cannabisDataset <- cannabisDataset %>%
  group_by(States, year) %>%
  mutate(
    cannabisLiberalization = case_when( 
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Fully Legal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana== 0 & legalizedRecreationalMarijuana == 0 ~ "Fully Illegal",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational & Decriminalized",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized & Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Medicinal & Recreational",
      TRUE ~ "None"
    )
  ) %>%

  select(-decriminalizedMarijuana, -legalizedMedicinalMarijuana, -legalizedRecreationalMarijuana)

head(cannabisDataset)
```

```{r}
cannabisDataset$crimeRate <- as.numeric(as.character(cannabisDataset$crimeRate))

cannabisDataset$recidivismRate <- as.numeric(as.character(cannabisDataset$recidivismRate))

cannabisDataset$population <- as.numeric(as.character(cannabisDataset$population))

cannabisDataset$alcoholism <- as.numeric(as.character(cannabisDataset$alcoholism))

cannabisDataset$unemploymentRate <- as.numeric(as.character(cannabisDataset$unemploymentRate))

cannabisDataset$medianHouseholdIncome <- as.numeric(as.character(cannabisDataset$medianHouseholdIncome))
```


```{r}
cannabisData2020 <- subset(cannabisDataset, year == 2020)
```

```{r}
library(ggplot2)
base2=ggplot(data=cannabisData2020,
             aes(x=cannabisLiberalization, y=crimeRate, # % not counts
                 fill=cannabisLiberalization)) + theme_minimal()
barDodge2= base2 +  geom_bar(stat="identity",
                            position ='dodge') 
barDodge2 + labs(title = "Is The Liberalization of Cannabis Laws Resulting in Decreased Crime Rates?",
                 subtitle = "Crime Rates by Cannabis Legalization Status 2020",
                 x="",
                 y="Crime Rates",
                 fill="Type of Liberalization")
```

```{r}
barStacked1 = base2 + geom_bar(stat = "identity",
                              position = 'stack')#default
barStacked1
```

```{r}
baseMEANs= ggplot(cannabisData2020, aes(x=cannabisLiberalization,
                      y=crimeRate)) 
jitterMEANs= baseMEANs + geom_jitter(colour="blue",
                             alpha=0.3 #transparency
                             )
jitterMEANs=jitterMEANs + geom_point(stat="summary") +
             geom_errorbar(stat="summary",width=.4)

jitterMEANs = jitterMEANs + geom_text_repel(aes(label=States),size=2.5) + 
  annotate("text", x = 1, y = 4400, label = "Source: cannabisData2020")
jitterMEANs 
```

```{r}
bivariate_plot <- ggplot(cannabisData2020, aes(x = crimeRate, y = population)) +
  geom_point(color = "skyblue", alpha = 0.7) +
  ggtitle("Crime Rate vs. Population in 2020") +
  labs(subtitle = "Relationship between crime rates and population size across states and D.C.",
       x = "Crime Rate",
       y = "Population Size") +
  annotate("text", x = 4000, y = 30000000, label = "Source: cannabisData2020") +
  scale_y_continuous(labels = scales::comma) + # Adding comma separator for y-axis
  theme_minimal()


library(ggrepel)
bivariate_plot=bivariate_plot + geom_text_repel(aes(label=States),size=2)



bivariate_plot
```



```{r}
baseBox=ggplot(data=cannabisData2020,
            aes(y=cannabisLiberalization))

```


```{r}
vio=baseBox+geom_violin(aes(x=crimeRate), fill="magenta",trim = F)
vio + coord_flip() 
```

