---
title: "Bivariate Plot"
author: "Alexandria Coombe"
format: 
  html: 
    embed-resources: true
    self-contained-math: true
---

```{r}
cannabisDataset <- read.csv("cannabisDataset.csv",
                        header = TRUE)
head(cannabisDataset)
```



```{r}
library(dplyr)
library(stringr)

cannabisDataset <- cannabisDataset %>%
  mutate_all(str_squish)

cannabisDataset <- cannabisDataset %>%
 mutate_all(~ifelse(tolower(.) %in% c("yes", "Yes"), 1, ifelse(tolower(.) %in% c("no", "No"), 0, .)))
```


```{r}
cannabisDataset <- cannabisDataset %>%
  group_by(States, year) %>%
  mutate(
    cannabisLiberalization = case_when( 
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Fully Legal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana== 0 & legalizedRecreationalMarijuana == 0 ~ "Fully Illegal",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational & Decriminalized",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized & Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Medicinal & Recreational",
      TRUE ~ "None"
    )
  ) %>%

  select(-decriminalizedMarijuana, -legalizedMedicinalMarijuana, -legalizedRecreationalMarijuana)

head(cannabisDataset)
```

```{r}
cannabisDataset$crimeRate <- as.numeric(as.character(cannabisDataset$crimeRate))

cannabisDataset$recidivismRate <- as.numeric(as.character(cannabisDataset$recidivismRate))

cannabisDataset$population <- as.numeric(as.character(cannabisDataset$population))

cannabisDataset$alcoholism <- as.numeric(as.character(cannabisDataset$alcoholism))

cannabisDataset$unemploymentRate <- as.numeric(as.character(cannabisDataset$unemploymentRate))

cannabisDataset$medianHouseholdIncome <- as.numeric(as.character(cannabisDataset$medianHouseholdIncome))
```


```{r}
cannabisData2020 <- subset(cannabisDataset, year == 2020)
```

```{r}
library(ggplot2)
base2=ggplot(data=cannabisData2020,
             aes(x=cannabisLiberalization, y=crimeRate, 
                 fill=cannabisLiberalization)) + theme_minimal()
barDodge2= base2 +  geom_bar(stat="identity",
                            position ='dodge') 
barDodge2 + labs(title = "Is The Liberalization of Cannabis Laws Resulting in Decreased Crime Rates?",
                 subtitle = "Crime Rates by Cannabis Legalization Status 2020",
                 x="",
                 y="Crime Rates",
                 fill="Type of Liberalization")
```

```{r}
barStacked1 = base2 + geom_bar(stat = "identity",
                              position = 'stack')#default
barStacked1
```

```{r}
library(ggrepel)
baseMEANs= ggplot(cannabisData2020, aes(x=cannabisLiberalization,
                      y=crimeRate)) 
jitterMEANs= baseMEANs + geom_jitter(colour="olivedrab",
                             alpha=0.3 #transparency
                             )
jitterMEANs=jitterMEANs + geom_point(stat="summary") +
             geom_errorbar(stat="summary",width=.4)

jitterMEANs = jitterMEANs + geom_text_repel(aes(label=States),size=2.5) + 
  annotate("text", x = 1, y = 4400, label = "Source: cannabisData2020")
jitterMEANs 
```


```{r}
baseMEANs <- ggplot(cannabisData2020, aes(x = cannabisLiberalization, y = crimeRate, color = cannabisLiberalization)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_point(stat = "summary") +
  geom_errorbar(stat = "summary", width = 0.4) +
  geom_text_repel(aes(label = States), size = 1, max.overlaps = 20) + 
  labs(title = "Relationship Between Cannabis Legalization and Crime Rate",
       subtitle = "Crime rate comparison across different levels of cannabis legalization",
       x = "Cannabis Legalization Status",
       y = "Crime Rate",
       caption = "Source: cannabisData2020") +
  scale_color_manual(name = "Cannabis Legalization Status",
                     values = c("Decriminalized & Medicinal" = "yellow3", 
                                "Fully Legal" = "olivedrab", 
                                "Medicinal" = "orange2", 
                                "Fully Illegal" = "red4")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

baseMEANs
```




```{r}
cannabisData2020$cannabisLiberalization <- factor(cannabisData2020$cannabisLiberalization, 
                                                  levels = c("Fully Illegal", "Medicinal", "Decriminalized & Medicinal", "Fully Legal"))

bivariatePlot <- ggplot(cannabisData2020, aes(x = cannabisLiberalization, y = crimeRate, color = cannabisLiberalization)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_point(stat = "summary") +
  geom_errorbar(stat = "summary", width = 0.4) +
  geom_text_repel(aes(label = States), size = 2, max.overlaps = 20) +
  labs(title = "Relationship Between Cannabis Legalization and Crime Rate",
       subtitle = "Crime rate comparison across different levels of cannabis legalization",
       x = "Cannabis Legalization Status",
       y = "Crime Rate",
       caption = "Source: cannabisData2020") +
   geom_hline(yintercept = 4500,
             linetype = "dashed",
             linewidth = 0.5,
             alpha = 0.5) +
  scale_color_manual(name = "Cannabis Legalization Status",
                     values = c("Decriminalized & Medicinal" = "yellow3", 
                                "Fully Legal" = "olivedrab", 
                                "Medicinal" = "orange2", 
                                "Fully Illegal" = "red4")) +
  annotate("text", x = 4, y = 4400, label = "Outlier") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 25, hjust = 1),
        legend.position = "right")

bivariatePlot


```

```{r}
library(ggplot2)
library(ggrepel)

cannabisData2020$cannabisLiberalization <- factor(cannabisData2020$cannabisLiberalization, 
                                                  levels = c("Fully Illegal", "Medicinal", "Decriminalized & Medicinal", "Fully Legal"))


bivariatePlotFinal <- ggplot(cannabisData2020, aes(x = cannabisLiberalization, y = crimeRate, color = cannabisLiberalization)) +
  geom_violin(alpha = 0.3, fill = NA) +
  geom_jitter(alpha = 0.5, width = 0.2) +
  stat_summary(fun = mean, geom = "point", size = 3, shape = 18, color = "black") +
  labs(title = "Relationship Between Cannabis Legalization and Crime Rate",
       subtitle = "U.S. Crime rate comparison across different levels of cannabis legalization",
       x = "Cannabis Legalization Status",
       y = "Crime Rate",
       caption = "Source: cannabisData2020") +
  geom_hline(yintercept = 4500, linetype = "dashed", color = "black", linewidth = 0.5, alpha = 0.5) +
  scale_color_manual(name = "Cannabis Legalization Status",
                     values = c("Fully Illegal" = "red4", 
                                "Medicinal" = "orange2", 
                                "Decriminalized & Medicinal" = "yellow3", 
                                "Fully Legal" = "olivedrab")) +
  annotate("text", x = 4.02, y = 4550, label = "Outlier: D.C.", size = 2, color = "black", hjust = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 25, hjust = 1),
        legend.position = "right")

print(bivariatePlotFinal)
```

```{r}
saveRDS(bivariatePlotFinal, file = "bivariatePlotFinal.RDS")
```









