---
title: "DACSS 690V Final Project"
author: "Alexandria Coombe"
format: 
  html: 
    embed-resources: true
    self-contained-math: true
---


```{r}
cannabisDataset <- read.csv("cannabisDataset.csv",
                        header = TRUE)
head(cannabisDataset)
```

```{r}
library(dplyr)
library(stringr)

cannabisDataset <- cannabisDataset %>%
  mutate_all(str_squish)

cannabisDataset <- cannabisDataset %>%
 mutate_all(~ifelse(tolower(.) %in% c("yes", "Yes"), 1, ifelse(tolower(.) %in% c("no", "No"), 0, .)))
```


```{r}
cannabisDataset <- cannabisDataset %>%
  group_by(States, year) %>%
  mutate(
    cannabisLiberalization = case_when( 
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Fully Legal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana== 0 & legalizedRecreationalMarijuana == 0 ~ "Fully Illegal",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 0 & legalizedRecreationalMarijuana == 1 ~ "Recreational & Decriminalized",
      decriminalizedMarijuana == 1 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 0 ~ "Decriminalized & Medicinal",
      decriminalizedMarijuana == 0 & legalizedMedicinalMarijuana == 1 & legalizedRecreationalMarijuana == 1 ~ "Medicinal & Recreational",
      TRUE ~ "None"
    )
  ) %>%

  select(-decriminalizedMarijuana, -legalizedMedicinalMarijuana, -legalizedRecreationalMarijuana)

head(cannabisDataset)
```


```{r}
cannabisDataset$crimeRate <- as.numeric(as.character(cannabisDataset$crimeRate))

cannabisDataset$recidivismRate <- as.numeric(as.character(cannabisDataset$recidivismRate))

cannabisDataset$population <- as.numeric(as.character(cannabisDataset$population))

cannabisDataset$alcoholism <- as.numeric(as.character(cannabisDataset$alcoholism))

cannabisDataset$unemploymentRate <- as.numeric(as.character(cannabisDataset$unemploymentRate))

cannabisDataset$medianHouseholdIncome <- as.numeric(as.character(cannabisDataset$medianHouseholdIncome))
```


```{r}
dim(cannabisDataset)
```

```{r}
names(cannabisDataset)
```

```{r}
str(cannabisDataset,width = 100,strict.width='cut')
```


```{r}
table(unlist(sapply(cannabisDataset, class)))
```

```{r}
head(cannabisDataset$cannabisLiberalization,20)
```


```{r}
absoluteT=table(cannabisDataset$cannabisLiberalization,
                exclude = 'nothing')
absoluteT
```

```{r}
propT=prop.table(absoluteT)*100

propT
```

```{r}
(tableFreq=as.data.frame(absoluteT))

names(tableFreq)=c("CannabisLiberalization","Count")
tableFreq$Percent=as.vector(propT)

tableFreq
```


```{r}
library(ggplot2)
base= ggplot(data = tableFreq, 
             aes(x = CannabisLiberalization, # horizontal
                 y = Count)) #vertical
```


```{r}
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') # notice the "stat"
plot1

```

```{r}
cannabis2020 <- subset(cannabisDataset, year == 2020)
```

```{r}
absoluteT2=table(cannabis2020$cannabisLiberalization,
                exclude = 'nothing')
absoluteT2
```

```{r}
propT2=prop.table(absoluteT2)*100

propT2
```


```{r}
(liberalizationFreq=as.data.frame(absoluteT2))

names(liberalizationFreq)=c("CannabisLiberalization","Count")
liberalizationFreq$Percent=as.vector(propT2)

liberalizationFreq
```


```{r}
library(ggplot2)
liberalization2020= ggplot(data = liberalizationFreq, 
             aes(x = CannabisLiberalization, # horizontal
                 y = Count)) #vertical
```

```{r}
liberalizationPlot2020 = liberalization2020 + geom_bar(fill ="grey",
                        stat = 'identity')
                        
liberalizationPlot2020
```

```{r}
titleText='Cannabis liberalization type across the United States'
sub_titleText='United States - 2020'
x.AxisText="Cannabis Liberalization Type"
y.AxisText="Number Of Instances"

liberalizationPlot2 = liberalizationPlot2020 + labs(title=titleText,
                     subtitle = sub_titleText,
                     x ="Cannabis Liberalization Type",  
                     y = "Number Of Instances", 
                     ) 
liberalizationPlot2
```


```{r}
# liberalization2020Percent= ggplot(data = liberalizationFreq, 
#              aes(x = CannabisLiberalization, # horizontal
#                  y = Percent)) #vertical
# 
# liberalizationPlot2 = liberalization2020Percent + geom_bar(fill ="lightblue",
#                         stat = 'identity') +
#                         theme_light()
# liberalizationPlot2

liberalization2020Percent <- ggplot(data = liberalizationFreq, 
                                    aes(x = factor(CannabisLiberalization), 
                                        y = Percent, 
                                        fill = factor(CannabisLiberalization)))

liberalizationPlot2 <- liberalization2020Percent +
  geom_bar(stat = 'identity') +
   scale_fill_manual(name = "Level of Cannabis Legalization", values = c("powderblue", "skyblue", "mediumblue", "darkblue"), labels = c("Decriminalized & Medicinally Legal", "Fully Illegal", "Fully Legal", "Medicinally Legal")) +
  theme_classic() 

liberalizationPlot2
```



```{r}
titleText='Cannabis liberalization type across the United States'
sub_titleText='United States - 2020'
x.AxisText="Cannabis Liberalization Type"
y.AxisText="Percent Of States Within The US"

liberalizationPercent2 = liberalizationPlot2 + labs(title=titleText,
                     subtitle = sub_titleText,
                     x ="Cannabis Liberalization Type",  
                     y = "Percent Of States Within The US", 
                     ) 
liberalizationPercent2
```


```{r}
liberalizationPercent2 <- liberalizationPlot2 +
  labs(title = titleText,
       subtitle = sub_titleText,
       x = x.AxisText,  
       y = y.AxisText) +
  geom_hline(yintercept = 25, 
             linetype = "dashed", 
             linewidth = 1.5, 
             alpha = 0.5) 

liberalizationPercent2
```

```{r}
liberalizationPercent2 <- liberalizationPlot2 +
  labs(title = titleText,
       subtitle = sub_titleText,
       x = x.AxisText,
       y = y.AxisText) +
  geom_hline(yintercept = 25,
             linetype = "dashed",
             linewidth = 1.5,
             alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 100, by = 5),
                     limits = c(0,55),
                     labels = scales::unit_format(suffix = '%')) +
  theme(plot.caption = element_text(hjust = 0), 
        plot.title = element_text(hjust = 0.5), 
        plot.subtitle = element_text(hjust = 0.5))

liberalizationPercent2

```
